### ISSUE TITLE
Option to allow alt URL

### ISSUE THREAD

**Issue by thezak48** [autobrr/dashbrr#26]
**Is your feature request related to a problem? Please describe.**
When you add a service with the URL being the docker dns name and then try to open the service it tries to send you to the internal docker shiz

**Describe the solution you'd like**
Option to add a alt URL for the open service thingy

**Describe alternatives you've considered**
Screaming

**Additional context**
![Image](https://github.com/user-attachments/assets/d1a12c7b-1ea9-431c-9dc7-1592cb8a51bd)

**Comment by bakerboy448** [comment]
"Access url"

**Comment by thezak48** [comment]
> "Access url"

Yeah that
