### ISSUE TITLE
Public and internal service URLs

### ISSUE THREAD

**Issue by jfroy** [autobrr/dashbrr#66]
**Is your feature request related to a problem? Please describe.**
I run media apps (autobrr, radarr, etc) on a Kubernetes cluster. They are behind an Ingress-Nginx proxy/load balancer that does https termination. These services's ingress are configured to use [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) to provide simple authentication using Ingress-Nginx's [external oauth authentication](https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/) feature. I also deployed dashbrr on this cluster (without oauth2-proxy).

Because of this, dashbrr cannot use the https URL to the media apps since it cannot complete the oauth flow. But it can use the internal service address provided by Kubernetes (e.g. radarr.default.svc.cluster.local).

While this works, it does make the link in the dashbrr frontend for the service unusable.

**Describe the solution you'd like**
Allow configuring separate "frontend" and "API" URLs for each service. The API URL is to be used by dashbrr to query the service, while the frontend URL is to be rendered in the UI for the user.

**Comment by s0up4200** [comment]
Hi there! This is already added in the develop branch actually! There's still a few places where `access_url` doesn't override `url`, but it will be fixed soon. (See https://github.com/autobrr/dashbrr/issues/51)

I would advice you to also run develop for the time being (or even https://github.com/autobrr/dashbrr/pull/63), as it has several improvements compared to the latest tagged release - with more to come. 

![Image](https://github.com/user-attachments/assets/7001f4f5-ced5-4ac7-9210-c3026f3614f5)

**Comment by jfroy** [comment]
Works great.
